# Generated by Django 2.0 on 2018-12-22 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageItem',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('employeeId', models.CharField(default=None, max_length=30)),
                ('storeId', models.IntegerField(blank=True, default=0)),
                ('locationId', models.IntegerField(blank=True, default=0)),
                ('barcode', models.CharField(default=None, max_length=30, unique=True)),
                ('description', models.CharField(default=None, max_length=500)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(default=None, max_length=30)),
                ('firstName', models.CharField(default=None, max_length=30)),
                ('lastName', models.CharField(default=None, max_length=30)),
                ('storeId', models.IntegerField(blank=True, default=0)),
                ('birthDate', models.DateField(blank=True)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('employmentType', models.CharField(default=None, max_length=30)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingTransaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('vendorId', models.IntegerField(blank=True, default=0)),
                ('employeeId', models.CharField(default=None, max_length=30)),
                ('total', models.FloatField(blank=True, default=None)),
                ('subtotal', models.FloatField(blank=True, default=None)),
                ('tax', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(default=None, max_length=30, unique=True)),
                ('name', models.CharField(default=None, max_length=30)),
                ('inStockQty', models.IntegerField(blank=True, default=0)),
                ('color', models.CharField(default=None, max_length=30)),
                ('ageRequirement', models.CharField(default=None, max_length=30)),
                ('purchasedPrice', models.FloatField(blank=True, default=0.0)),
                ('salePrice', models.FloatField(blank=True, default=0.0)),
                ('department', models.CharField(default=None, max_length=30)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='OutgoingTransaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('storeId', models.IntegerField(blank=True, default=0)),
                ('employeeId', models.CharField(default=None, max_length=30, null=True)),
                ('tax', models.FloatField(blank=True, default=0.0925, null=True)),
                ('subtotal', models.FloatField(blank=True, default=None, null=True)),
                ('total', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30)),
                ('address', models.CharField(default=None, max_length=50)),
                ('hoursOpen', models.CharField(default=None, max_length=150)),
                ('phoneNumber', models.CharField(default=None, max_length=30)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default=None, max_length=30)),
                ('transactionId', models.IntegerField(blank=True, default=0)),
                ('transactionType', models.CharField(default=None, max_length=30)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('tax', models.FloatField(blank=True, default=0.0925, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default=None, max_length=100)),
                ('phoneNumber', models.CharField(default=None, max_length=30)),
                ('name', models.CharField(default=None, max_length=30)),
                ('hoursOpen', models.CharField(default=None, max_length=150)),
            ],
            options={
                'db_table': '',
            },
        ),
    ]
